### ISSUE TITLE
Clock should operate at 15 minute intervals with default time set to nearest 15 minute interval.

### ISSUE THREAD

**Issue by djensenius** [condomanagement/condo-web#40]

**Comment by MaggieShan** [comment]
Sorry, I'm looking to get this done soon! The text change error is fixed, and the clock forces users to the nearest 15 minute interval as desired. 

Current problems I'm looking into:
* The dial is unable to "snap" to 15 minute intervals on mobile, so I'm looking into rounding the values after the user makes their selection
* On mobile, the default values also aren't showing as desired, so I'm looking into giving the component the proper format to display.

**Comment by djensenius** [comment]
The snapping to 15 minutes won't work on mobile. At least iOS, it's not supported 😔

https://caniuse.com/#search=timepicker
