### ISSUE TITLE
End time should be secretly shorter

### ISSUE THREAD

**Issue by djensenius** [condomanagement/condo-web#49]
When making a reservation it could be technically longer than the time limit, or technically overlap with another reservation.

Reservation 1:
6:00 - 6:30PM

Reservation 2:
6:30 - 7:00PM

Technically overlaps.

**Comment by djensenius** [comment]
Looks like what I thought would happen doesn't happen. @MaggieShan could you confirm?

**Comment by MaggieShan** [comment]
I can confirm that reservations are able to overlap, however I have not been able to reserve them for longer than the time limit.

**Comment by djensenius** [comment]
To clarify, they can overlap for the ending minute of one reservation and the beginning of the next? But not for more than that, right?
