### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by djensenius** [condomanagement/condo-web#60]
great job making the reserve amenity button specific to the amenity (eg reserve bbq in zone c) , and then showing the confirmation message “amenity reserved” - the confirmation message could also point people to see their reservations in the My Reservations section and that could possibly be linked as they might not have seen that in the menu yet if they didn’t expand the mini drawer ui

----

Let's also make a button to make another reservation

**Comment by MaggieShan** [comment]
Fix with [PR #43](https://github.com/condomanagement/condo-api/pull/43)
