### ISSUE TITLE
Home screen and login for parking 

### ISSUE THREAD

**Issue by tomh009** [condomanagement/condo-web#66]
https://arrowlofts.org should really be a home page with the different options available, displaying the parking by default is a bit confusing.

And parking should use the same login mechanism, too.

**Comment by djensenius** [comment]
Fixed. No PR because I forgot to make a branch and pushed to master. 😢

**Comment by tomh009** [comment]
:) Thanks!

Tom

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by djensenius** [comment]
Should be noted when logged in default navigation is amenity reservation.

**Comment by tomh009** [comment]
OK. You will also change parking to use login? Should I create a new github ticket for it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by djensenius** [comment]
I think parking should be able to be done by anyone (visitors for example). What I can do is if the user is logged in remove the contact and unit fields. I think I already have an issue for this part. It’s a decent sized task as I just used the old parking API code and it’s totally unaware of accounts.  On Sat, Aug 29, 2020 at 1:41 PM, tomh009 <notifications@github.com> wrote:  
OK. You will also change parking to use login? Should I create a new github ticket for it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tomh009** [comment]
Not urgent anyway. (And a visitor can still do it as long as they know the resident's email address.) Let's discuss this later, back of the queue for now!

Tom
________________________________
